### ISSUE TITLE
Missing file listed in datapackage.json

### ISSUE THREAD

**Issue by larsyencken** [open-numbers/ddf--unfao--faostat#1]
Hi @semio ! o/

An automatic system just picked up a missing file in this repo. Frictionless fails to load the package with this error:

```
frictionless.exception.FrictionlessException: [scheme-error] The data source could not be successfully loaded: [Errno 2] No such file or directory: '/home/owid/.owid/git/open-numbers/ddf--unfao--faostat/datapoints/ddf--datapoints--recovered_fibre_pulp_production_fea2--by--geo--year.csv'
```

It looks like this specific file is in the package metadata but not actually in the repo. It's not at all urgent for us, just giving you a heads up.

**Comment by semio** [comment]
Oh, hi Lars! I was updating this dataset to make master branch up to date with latest FAOSTAT data, but forgot to update the datapackage.json after updating the csv files. Sorry for any inconvenience caused by my mistake!

I have re-generated the datapackage.json so it should be ok to load this dataset. 

The indicator `recovered_fibre_pulp_production_fea2` was removed from FAOSTAT data, so if your pipeline depends on this indicator you should find alternative indicators or use earlier commit that has this indicator.

**Comment by larsyencken** [comment]
Ah, thanks @semio ! We aren't using this indicator, more doing a bulk import of FAO. It's not used in anything live at the moment, so we weren't too affected. Have a great weekend o/

**Comment by semio** [comment]
I see. Thanks, have a great weekend too and happy Halloween 🎃
